# Goal
float64[] rotations
float64[] translations
string name
---
# Result
bool success

---
# Feedback
bool pick_planning_success
bool picking_success
bool place_planning_success
bool placing_success
