sensor_msgs/Image predicted_image
sensor_msgs/Image depth_map
float64[] K_matrix
---
sensor_msgs/Image predicted_image
sensor_msgs/Image predicted_image_bbox
sensor_msgs/Image depth_map
float64[] rotations
float64[] boxes
float64[] scores
float64[] translations